In [27]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

In [ ]:
#################### SKIP CELLS to CELL labeled:  "# START - Load dataset" ############################

In [7]:
# *** SKIP CELL ***

# Load dataset 
## data = pd.read_csv('static/heart.csv')

## data.head(10)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
5,39,M,NAP,120,339,0,Normal,170,N,0.0,Up,0
6,45,F,ATA,130,237,0,Normal,170,N,0.0,Up,0
7,54,M,ATA,110,208,0,Normal,142,N,0.0,Up,0
8,37,M,ASY,140,207,0,Normal,130,Y,1.5,Flat,1
9,48,F,ATA,120,284,0,Normal,120,N,0.0,Up,0

In [8]:
# *** SKIP CELL ***

## print(data.columns)

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [26]:
# *** SKIP CELL ***

# List of columns to convert
## columns_to_convert = ['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope']

# Loop through the columns and create binary columns
## for column in columns_to_convert:
    ## unique_values = data[column].unique()
    ## for value in unique_values:
       ## data[f'{column}_{value.lower()}'] = (data[column] == value).astype(int)

# Drop the original columns
## data.drop(columns=columns_to_convert, inplace=True)

## print(data.head(10))

In [5]:
# *** SKIP CELL ***

# create a new variable to avoid confusion
## data2 = data

## data2.head(10)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
5,39,M,NAP,120,339,0,Normal,170,N,0.0,Up,0
6,45,F,ATA,130,237,0,Normal,170,N,0.0,Up,0
7,54,M,ATA,110,208,0,Normal,142,N,0.0,Up,0
8,37,M,ASY,140,207,0,Normal,130,Y,1.5,Flat,1
9,48,F,ATA,120,284,0,Normal,120,N,0.0,Up,0

In [23]:
# *** SKIP CELL ***

## print(data2.columns)

Index(['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak',
       'HeartDisease', 'Sex_m', 'Sex_f', 'ChestPainType_ata',
       'ChestPainType_nap', 'ChestPainType_asy', 'ChestPainType_ta',
       'RestingECG_normal', 'RestingECG_st', 'RestingECG_lvh',
       'ExerciseAngina_n', 'ExerciseAngina_y', 'ST_Slope_up', 'ST_Slope_flat',
       'ST_Slope_down'],
      dtype='object')

In [24]:
# *** SKIP CELL ***

# data2.to_csv('heart_integer_v01.csv', index=False)

In [ ]:
############################################################

In [ ]:
#################### START BELOW ############################

In [28]:
# START - Load dataset 
data2 = pd.read_csv('static_[null]/heart_integer_v01.csv')

data2.head(10)

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_m,Sex_f,ChestPainType_ata,...,ChestPainType_asy,ChestPainType_ta,RestingECG_normal,RestingECG_st,RestingECG_lvh,ExerciseAngina_n,ExerciseAngina_y,ST_Slope_up,ST_Slope_flat,ST_Slope_down
0,40,140,289,0,172,0.0,0,1,0,1,...,0,0,1,0,0,1,0,1,0,0
1,49,160,180,0,156,1.0,1,0,1,0,...,0,0,1,0,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,1,0,1,...,0,0,0,1,0,1,0,1,0,0
3,48,138,214,0,108,1.5,1,0,1,0,...,1,0,1,0,0,0,1,0,1,0
4,54,150,195,0,122,0.0,0,1,0,0,...,0,0,1,0,0,1,0,1,0,0
5,39,120,339,0,170,0.0,0,1,0,0,...,0,0,1,0,0,1,0,1,0,0
6,45,130,237,0,170,0.0,0,0,1,1,...,0,0,1,0,0,1,0,1,0,0
7,54,110,208,0,142,0.0,0,1,0,1,...,0,0,1,0,0,1,0,1,0,0
8,37,140,207,0,130,1.5,1,1,0,0,...,1,0,1,0,0,0,1,0,1,0
9,48,120,284,0,120,0.0,0,0,1,1,...,0,0,1,0,0,1,0,1,0,0

In [29]:
print(data2.columns)

Index(['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak',
       'HeartDisease', 'Sex_m', 'Sex_f', 'ChestPainType_ata',
       'ChestPainType_nap', 'ChestPainType_asy', 'ChestPainType_ta',
       'RestingECG_normal', 'RestingECG_st', 'RestingECG_lvh',
       'ExerciseAngina_n', 'ExerciseAngina_y', 'ST_Slope_up', 'ST_Slope_flat',
       'ST_Slope_down'],
      dtype='object')

In [30]:
# Drop specified columns // DONT NEED COLUMNS b/c Binary Output: M/F
columns_to_drop = ['Sex_f', 'ExerciseAngina_n']
data2 = data2.drop(columns=columns_to_drop)

# Verify the changes
print(data2.columns)

Index(['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak',
       'HeartDisease', 'Sex_m', 'ChestPainType_ata', 'ChestPainType_nap',
       'ChestPainType_asy', 'ChestPainType_ta', 'RestingECG_normal',
       'RestingECG_st', 'RestingECG_lvh', 'ExerciseAngina_y', 'ST_Slope_up',
       'ST_Slope_flat', 'ST_Slope_down'],
      dtype='object')

In [31]:
# Split into features (X) and target variable (y)
X = data2.drop('HeartDisease', axis=1)
y = data2['HeartDisease']

In [32]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [33]:
# Import the Logistic Regression module
from sklearn.linear_model import LogisticRegression

# Create an instance of Logistic Regression
logistic_classifier = LogisticRegression(random_state=42, max_iter=1000)

# Fit the model on the training data
logistic_classifier.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = logistic_classifier.predict(X_test)

/Users/michaelstrati/anaconda3/envs/dev/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [34]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Make predictions on the testing data
y_pred = logistic_classifier.predict(X_test)

print("----------------------------------------------------------")

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("----------------------------------------------------------")

# Other classification metrics
print(classification_report(y_test, y_pred))

print("----------------------------------------------------------")

# Confusion matrix
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

print("----------------------------------------------------------")

----------------------------------------------------------
Accuracy: 0.8532608695652174
----------------------------------------------------------
              precision    recall  f1-score   support

           0       0.80      0.87      0.83        77
           1       0.90      0.84      0.87       107

    accuracy                           0.85       184
   macro avg       0.85      0.86      0.85       184
weighted avg       0.86      0.85      0.85       184

----------------------------------------------------------
Confusion Matrix:
 [[67 10]
 [17 90]]
----------------------------------------------------------